name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # In order for Chromatic to correctly determine baseline commits,
          # we need access to the full Git history graph.
          fetch-depth: 0
      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
